# Generated by Django 4.0.2 on 2022-02-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloging',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='bloging',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
