# Generated by Django 4.0.2 on 2022-02-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_bloging_description_alter_bloging_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloging',
            name='description',
            field=models.TextField(max_length=1250),
        ),
    ]
